version: '3.7'
services:

  mysql-standalone:
    image: mysql:8.0.26
    restart: always
    environment:
      - MYSQL_DATABASE=clientedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - production-network
    ports: 
      - 3333:3306
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - production-network
    depends_on:
      - mysql-standalone

networks:
  production-network:
    driver: bridge